services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_ADMIN_PASSWORD
      POSTGRES_DB: inbox_swap
    ports:
      - "5433:5432"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U", "postgres",
          "-d", "inbox_swap",
        ]
      interval: 30s
      timeout: 15s
      retries: 3
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env